version: '3.9'
services:

  backend:
    profiles:
      - all
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:80'
    environment:
      ConnectionStrings__CandyDatabase: Host=postgres:5432;Database=postgres;Username=postgres;Password=postgres 
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: on-failure
    command: postgres -c 'max_connections=200'
    volumes:
      - postgres-candy-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: UTC
      PGTZ: UTC
    ports:
      - '5432:5432'

volumes:
  postgres-candy-data:
